COMMENT =	HTML-encoding text filter

DISTNAME   =	txt2html-0.1.0
CATEGORIES =	mystuff textproc
HOMEPAGE   =	https://dl.danielmoch.com/txt2html

MASTER_SITES =		https://dl.danielmoch.com/txt2html/

# ISC
PERMIT_PACKAGE =	Yes

PREFIX      =	/var/git

TEST_TARGET =	test
ALL_TARGET =	all

.include <bsd.port.mk>
