COMMENT =	url shortener and go-get redirector

DISTNAME   =	shrt-1.0.4
CATEGORIES =	mystuff www
HOMEPAGE   =	https://git.danielmoch.com/shrt/about/
PKGPATH    =	mystuff/shrt

MASTER_SITES =		https://dl.danielmoch.com/shrt/

# ISC
PERMIT_PACKAGE =	Yes

PREFIX      =	/var/www

TEST_TARGET =	test
ALL_TARGET =	all

.include <bsd.port.mk>
